# Generated by Django 2.1.7 on 2019-03-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p', models.CharField(max_length=309)),
                ('q', models.CharField(max_length=309)),
            ],
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=617)),
                ('g', models.CharField(max_length=617)),
            ],
        ),
        migrations.AddField(
            model_name='privatekey',
            name='public_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_key', to='capsule.PublicKey'),
        ),
    ]
